version: "3"

services:
  nginx: 
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports: 
      - "8080:80"
    links: 
      - php
    volumes:
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    tty: true
    volumes:
      - ./src:/var/www/html
      - ./docker/development/api/php.ini:/usr/local/etc/php/conf.d/php.ini:delegated
